a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('É só espaços?', a.isspace())
print('É alfabético?', a.isalpha())
print('É numérico?', a.isnumeric())
print('É alfanumérico?', a.isalnum())
print('É decimal?', a.isdecimal())
print('Está em minúsculas?', a.islower())
print('Está em maiúsculas?', a.isupper())
print('Está capitalizada?', a.istitle())
